### ISSUE TITLE
DB Setup

### ISSUE THREAD

**Issue by bwdmonkey** [leesw98/FreeEyeOut#12]
Options (SQL): MySQL, MariaDB, PostgreSQL, Oracle, Microsoft SQL Server
Options (NoSQL): Google Firebase

**Comment by bobheadxi** [comment]
@zhulia960821 Insert course data into database as well via `pipelines.py`
See [pipeline](https://github.com/leesw98/FreeEyeOut/blob/master/scraper/free_scraper/pipelines.py) ([documentation](https://docs.scrapy.org/en/latest/topics/item-pipeline.html))
See [parser](https://github.com/leesw98/FreeEyeOut/blob/master/scraper/free_scraper/spiders/parsers/course_parser.py) ([selector docs](https://docs.scrapy.org/en/latest/topics/selectors.html), [xpath and shell](https://docs.scrapy.org/en/latest/topics/shell.html))
and learn about [Scrapy](https://scrapy.org)

Also see [sleuth's crawler](https://github.com/ubclaunchpad/sleuth/tree/master/sleuth_crawler), which uses a different scrapy crawler class (`BroadCrawler`) but demonstrates some nice item pipelining and unit testing and stuff

- [ ] Test if scraper works (#13)
- [ ] Decide on database hosting option (or do it locally)
- [ ] Build insertion (1 course per row, 1 table for everything)
